SELECT * FROM TABELA_DE_CLIENTES;

SELECT NOME, LOWER(NOME) AS NOME_MINUSCULO FROM TABELA_DE_CLIENTES;

SELECT NOME, LOWER(NOME) AS NOME_MINUSCULO, UPPER(NOME) AS NOME_MAIUSCULO FROM TABELA_DE_CLIENTES;

SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO, ' - ', CEP) AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES;

SELECT NOME , ENDERECO_1 +  ' ' + BAIRRO + ' ' + CIDADE + ' ' + ESTADO + ' - ' + CEP AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, LEFT(NOME_DO_PRODUTO,3) AS TRES_PRIMEIROS_CHAR FROM TABELA_DE_PRODUTOS

SELECT TAMANHO, REPLACE((REPLACE(TAMANHO, 'Litros', 'L')),'Litro','L') AS TAMANHO_MODIFICADO FROM TABELA_DE_PRODUTOS;

SELECT GETDATE()

SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, 10, GETDATE()) AS DATA_DAQUI_10_DIAS

SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, 10, GETDATE()) AS DATA_DAQUI_10_DIAS
, DATEADD(DAY, -48, GETDATE()) AS DATA_48_DIAS_ATRAS

SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, 10, GETDATE()) AS DATA_DAQUI_10_DIAS
, DATEADD(DAY, -48, GETDATE()) AS DATA_48_DIAS_ATRAS, DATEDIFF (DAY, '2022-01-01', GETDATE()) AS DIAS_DESDE_INICIO_ANO


SELECT GETDATE() DATA_HOJE, DATEPART(DAY, GETDATE()) AS DIA_DE_HOJE

SELECT ISDATE('2020-02-29')


SELECT ISDATE(DATETIMEFROMPARTS(2020,02,29,00,00,00,00))

SELECT ROUND(3.437, 2),  ROUND(3.433, 2)

SELECT ROUND(3.437, 2),  ROUND(3.433, 2), CEILING(3.433)

SELECT ROUND(3.437, 2),  ROUND(3.433, 2), CEILING(3.433), FLOOR(3.433)

SELECT ROUND(3.437, 2),  ROUND(3.433, 2), CEILING(3.433), FLOOR(3.433), POWER (12, 2)

SELECT ROUND(3.437, 2),  ROUND(3.433, 2), CEILING(3.433), FLOOR(3.433), POWER (12, 2), EXP(3)

SELECT ROUND(3.437, 2),  ROUND(3.433, 2), CEILING(3.433), FLOOR(3.433), POWER (12, 2), EXP(3),
SQRT(300)

SELECT ROUND(3.437, 2),  ROUND(3.433, 2), CEILING(3.433), FLOOR(3.433), POWER (12, 2), EXP(3),
SQRT(300), ABS(10), ABS(-10)

SELECT CONVERT(VARCHAR(10), GETDATE(), 121)

SELECT * FROM TABELA_DE_CLIENTES

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 121)
FROM TABELA_DE_CLIENTES;

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 106)
FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS;


SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', PRECO_DE_LISTA) as PRECO 
FROM TABELA_DE_PRODUTOS;