	SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS NUMERO_NOTAS 
FROM TABELA_DE_VENDEDORES TV  
INNER JOIN NOTAS_FISCAIS NF
ON NF.MATRICULA = TV.MATRICULA 
GROUP BY NF.MATRICULA, TV.NOME;


SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

	
	
	
	
	
	
	
	
	
	SELECT 
TC.CPF AS CPF_DO_CADASTRO, TC.NOME AS NOME_DO_CLIENTE, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF;

SELECT DISTINCT 
TC.CPF AS CPF_DO_CADASTRO, TC.NOME AS NOME_DO_CLIENTE, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF;

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2,
BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, GENERO,
LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
VALUES ('23412632331', 'Juliana Silva', 'Rua Tramandaí', ' ', 'Bangu', 'Rio de
Janeiro', 'RJ', '23400000', '1989-02-04', 33, 'F', '180000', '24500', 0);

SELECT DISTINCT 
TC.CPF AS CPF_DO_CADASTRO, TC.NOME AS NOME_DO_CLIENTE, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
LEFT JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF;

SELECT DISTINCT 
TC.CPF AS CPF_DO_CADASTRO, TC.NOME AS NOME_DO_CLIENTE, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
LEFT JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF 
WHERE NF.CPF IS NULL

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;

SELECT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR 
FROM TABELA_DE_CLIENTES TC 
INNER JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;

SELECT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
INNER JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;

SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
INNER JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;

SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
RIGHT JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;

SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
RIGHT JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO 
WHERE TC.NOME IS NULL;

SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
LEFT JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO 
WHERE TV.NOME IS NULL;


SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
FULL JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;